# Generated by Django 4.1.5 on 2024-04-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_locality_customer_phone_remove_customer_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
